import { chromium } from "/opt/node-tools/node_modules/playwright/index.mjs";
import http from "http"; import fs from "fs"; import path from "path";
const dir = path.resolve("out");
const srv = http.createServer((q, r) => { const f2 = path.join(dir, (q.url === "/" ? "index.html" : q.url).split("?")[0]); r.setHeader("content-type", f2.endsWith(".js") ? "text/javascript" : f2.endsWith(".png") ? "image/png" : "text/html"); fs.createReadStream(f2).on("error", () => { r.statusCode = 404; r.end(); }).pipe(r); }).listen(8770);
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
await p.goto("http://localhost:8770/"); await p.waitForFunction(() => window.__start); await p.evaluate(() => window.__start()); await p.waitForTimeout(1500);
await p.evaluate(async () => { const w = [...document.querySelectorAll("[data-focusable]")].find((e) => e.__props?.onOptionsButton); w.__props.onGamepadDirection({ detail: { button: 10 }, preventDefault() {}, stopPropagation() {} }); });
await p.waitForTimeout(1500);
await p.screenshot({ path: "band.png", clip: { x: 0, y: 0, width: 1280, height: 200 } });
await b.close(); srv.close();
