import { chromium } from "/opt/node-tools/node_modules/playwright/index.mjs";
import http from "http"; import fs from "fs"; import path from "path";
const dir = path.resolve("out");
const srv = http.createServer((q, r) => { const f2 = path.join(dir, (q.url === "/" ? "index.html" : q.url).split("?")[0]); r.setHeader("content-type", f2.endsWith(".js") ? "text/javascript" : f2.endsWith(".png") ? "image/png" : "text/html"); fs.createReadStream(f2).on("error", () => { r.statusCode = 404; r.end(); }).pipe(r); }).listen(8767);
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs = []; p.on("pageerror", (e) => errs.push(String(e)));
await p.goto("http://localhost:8767/");
await p.waitForFunction(() => window.__start); await p.evaluate(() => window.__start());
await p.waitForTimeout(1200);
const r = await p.evaluate(async () => {
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const fsx = () => [...document.querySelectorAll("[data-focusable]")];
  const wheel = fsx().find((e) => e.__props?.onOptionsButton);
  const sec = fsx().find((e) => e.__props?.onButtonDown && e.__props?.onGamepadDirection && !e.__props?.onOptionsButton);
  const box = wheel.closest("[data-spindeck-wheel]").parentElement.parentElement;
  const ev = (button, extra = {}) => ({ detail: { button, ...extra }, preventDefault() { this.p = true; }, stopPropagation() {} });
  const log = [];
  const state = () => box.style.top;
  wheel.__props.onGamepadDirection(ev(10)); await sleep(500); log.push(["▼ from wheel", state()]);
  log.push(["focus after slide", document.activeElement?.textContent]);
  const vs = document.getElementById("orighome");
  log.push(["tab row top px", Math.round(document.getElementById("tabs").getBoundingClientRect().top)]);
  await sleep(800);
  sec.__props.onGamepadDirection(ev(9)); await sleep(500); log.push(["▲ at top", state()]);
  await sleep(900);
  wheel.__props.onGamepadDirection(ev(10)); await sleep(1100);
  log.push(["▼ again", state()]);
  const row2 = [...document.querySelectorAll("button")].find((b) => b.textContent === "row2"); row2.focus();
  const bEv = ev(2); sec.__props.onButtonDown(bEv); await sleep(50);
  log.push(["Ⓑ deep → focus", document.activeElement?.textContent, "consumed", !!bEv.p]);
  const bEv2 = ev(2); sec.__props.onButtonDown(bEv2); log.push(["Ⓑ at top consumed (should be false → Steam)", !!bEv2.p]);
  row2.focus(); sec.__props.onGamepadDirection(ev(9)); await sleep(100);
  const row1 = [...document.querySelectorAll("button")].find((b) => b.textContent === "row1"); row1.focus();
  sec.__props.onGamepadDirection(ev(9)); await sleep(500); log.push(["held ▲ reaching top", state()]);
  await sleep(400); sec.__props.onGamepadDirection(ev(9)); await sleep(500); log.push(["fresh ▲ at top", state()]);
  // wheel ▲ right after arriving is ignored, later goes to search
  wheel.__props.onGamepadDirection(ev(9)); log.push(["wheel ▲ just arrived → nav", window.__nav ?? "none"]);
  await sleep(800); wheel.__props.onGamepadDirection(ev(9)); log.push(["wheel ▲ later → nav", window.__nav ?? "none"]);
  return log;
});
console.log(r.map((x) => x.join(" | ")).join("\n")); console.log("pageerrors:", errs);
await b.close(); srv.close();
